title: Art of Cognizance
theme: minima
author: Muhiminul Islam Osim  
email: muhiminul@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is not only about competitive programming and other CS
  fundamentals, but also about the cognizance of life. Some
  fragrance about philosophy may also be found.

# social links
twitter_username: MuhiminulOsim
github_username:  MuhiminOsim

show_excerpts: true # set to false to remove excerpts on the homepage
